name: comp2212-csv-query-language
version: 0.1.0.0
github: "githubuser/comp2212-csv-query-language"
license: BSD-3-Clause
author: "Author name here"
maintainer: "example@example.com"
copyright: "2025 Author name here"
extra-source-files:
- README.md
- CHANGELOG.md

description: A domain-specific language for querying CSV files

dependencies:
- base >= 4.7 && < 5
- array
- containers
- directory
- mtl

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  exposed-modules:
    - CSV
    - Lexer
    - Parser
    - Interpreter
  verbatim: |
    build-tool-depends:
      alex:alex,
      happy:happy

executables:
  comp2212-csv-query-language-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - comp2212-csv-query-language

tests:
  comp2212-csv-query-language-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - comp2212-csv-query-language